services:
  web:
    build: .
    ports:
      - "80:5000"
    environment:
      - NAME=AzureDocker
      - POSTGRES_PASSWORD=mysecretpassword
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
